# Generated by Django 4.2.30 on 2026-10-09 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('category', models.CharField(max_length=60)),
                ('unit_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('current_stock', models.IntegerField()),
                ('reorder_lead_time_days', models.PositiveSmallIntegerField()),
                ('persona', models.CharField(blank=True, max_length=30)),
            ],
            options={
                'ordering': ['sku'],
            },
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('as_of', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('stock_on_hand', models.IntegerField()),
                ('daily_demand', models.FloatField()),
                ('reorder_point', models.FloatField()),
                ('should_reorder', models.BooleanField()),
                ('recommended_qty', models.PositiveIntegerField()),
                ('urgency', models.CharField(max_length=10)),
                ('confidence', models.CharField(max_length=10)),
                ('reason', models.TextField()),
                ('outcome_actual_demand', models.FloatField(blank=True, null=True)),
                ('outcome_stockout', models.BooleanField(blank=True, null=True)),
                ('outcome_checked_at', models.DateTimeField(blank=True, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='inventory.product')),
            ],
            options={
                'ordering': ['-as_of', 'product__sku'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('quantity', models.PositiveIntegerField()),
                ('type', models.CharField(choices=[('SALE', 'Sale'), ('RESTOCK', 'Restock')], max_length=8)),
                ('split', models.CharField(default='train', max_length=8)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='inventory.product')),
            ],
            options={
                'ordering': ['date', 'id'],
                'indexes': [models.Index(fields=['product', 'date'], name='inventory_t_product_af0d44_idx')],
            },
        ),
    ]
